apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "workadventure.back.labels" . | nindent 4 }}
  name: {{ include "workadventure.back.name" . }}
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: http
  - port: 50051
    targetPort: 50051
    name: internal
  selector:
    {{- include "workadventure.back.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
  type: ClusterIP