apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "workadventure.chat.labels" . | nindent 4 }}
  name: {{ include "workadventure.chat.name" . }}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    {{- include "workadventure.chat.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
  type: ClusterIP