apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: chat
    app: workadventure
  name: chat
spec:
  replicas: 1
  selector:
    matchLabels:
      component: chat
      app: workadventure
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        component: chat
        app: workadventure
    spec:
      containers:
        - name: chat
          image: {{ .Values.global.imageRegistry }}/thecodingmachine/workadventure-chat:{{ .Chart.AppVersion }}
          envFrom:
            - configMapRef:
                name: workadventure
          # env:
          #   - name: PUSHER_URL
          #     value: https://${PUSHER_HOST}
          ports:
            - containerPort: 80
              name: http
          resources: {}
      restartPolicy: Always
