apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "workadventure.chat.labels" . | nindent 4 }}
  name: {{ include "workadventure.chat.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "workadventure.chat.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "workadventure.chat.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "workadventure.serviceAccountName" . }}
      containers:
        - name: chat
          image: {{ .Values.global.imageRegistry }}/thecodingmachine/workadventure-chat:{{ .Chart.AppVersion }}
          envFrom:
            - configMapRef:
                name: {{ include "workadventure.fullname" . }}
          # env:
          #   - name: PUSHER_URL
          #     value: https://${PUSHER_HOST}
          ports:
            - containerPort: 80
              name: http
          resources: {}
      restartPolicy: Always
