apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "workadventure.ejabberd.labels" . | nindent 4 }}
  name: {{ include "workadventure.ejabberd.name" . }}
spec:
  ports:
    - name: "5443"
      port: 5443
      targetPort: 5443
  selector:
    {{- include "workadventure.ejabberd.selectorLabels" . | nindent 4 }}