apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "workadventure.ejabberd.labels" . | nindent 4 }}
  name: {{ include "workadventure.ejabberd.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "workadventure.ejabberd.selectorLabels" . | nindent 6 }}
    type: Recreate
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "workadventure.ejabberd.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "workadventure.serviceAccountName" . }}
      initContainers:
        - name: init
          image: {{ .Values.global.imageRegistry }}/workadventure/ejabberd:v1
          command:
            - /bin/sh
            - -c
            - cp /opt/ejabberd/conf/* /tmp/ejabberd/conf/
          volumeMounts:
            - name: ejabberd-template
              mountPath: /opt/ejabberd/conf/ejabberd.template.yml
              subPath: ejabberd.template.yml
            - name: conf
              mountPath: /tmp/ejabberd/conf
      containers:
        - name: ejabberd
          image: {{ .Values.global.imageRegistry }}/workadventure/ejabberd:v1
          envFrom:
            - configMapRef:
                name: {{ include "workadventure.fullname" . }}
            - secretRef:
                name: {{ include "workadventure.fullname" . }}
          env:
            - name: CTL_ON_CREATE
              value: register admin ejabberd.{{ .Values.domain }} mySecretPassword
            - name: JWT_SECRET
              value: MyJwtSecret
          ports:
            - containerPort: 5443
          resources: {}
          volumeMounts:
            - name: conf
              mountPath: /opt/ejabberd/conf
      restartPolicy: Always
      volumes:
        - name: ejabberd-template
          configMap:
            name: {{ include "workadventure.ejabberd.name" . }}
            #defaultMode: 0666
        - name: conf
          emptyDir: {}
