apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "workadventure.icon.labels" . | nindent 4 }}
  name: {{ include "workadventure.icon.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "workadventure.icon.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "workadventure.icon.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "workadventure.serviceAccountName" . }}
      containers:
        - name: icon
          image: {{ .Values.global.imageRegistry }}/matthiasluedtke/iconserver:v3.13.0
          ports:
            - containerPort: 8080
              name: http
          resources: {}
      restartPolicy: Always