apiVersion: v1
kind: Service
metadata:
  labels:
    component: map-storage
    app: workadventure
  name: map-storage
spec:
  ports:
  - name: port-1
    port: 3000
    protocol: TCP
    targetPort: 3000
  - name: port-2
    port: 50053
    protocol: TCP
    targetPort: 50053
  selector:
    component: map-storage
    app: workadventure
  sessionAffinity: None
  type: ClusterIP
