apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "workadventure.map-storage.labels" . | nindent 4 }}
  name: {{ include "workadventure.map-storage.name" . }}
spec:
  ports:
  - name: port-1
    port: 3000
    protocol: TCP
    targetPort: 3000
  - name: port-2
    port: 50053
    protocol: TCP
    targetPort: 50053
  selector:
    {{- include "workadventure.map-storage.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
  type: ClusterIP
