apiVersion: v1
kind: Service
metadata:
  labels:
    component: play
    app: workadventure
  name: play
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    component: play
    app: workadventure
  sessionAffinity: None
  type: ClusterIP
