apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "workadventure.labels" . | nindent 4 }}
  name: {{ include "workadventure.fullname" . }}
type: Opaque
data:
  AWS_SECRET_ACCESS_KEY: 
  BBB_SECRET: OGNkOGVmNTJlOGUxMDE1NzRlNDAwMzY1YjU1ZTExYTY=
  EJABBERD_JWT_SECRET: TXlKd3RTZWNyZXQ=
  EJABBERD_PASSWORD: bXlTZWNyZXRQYXNzd29yZA==
  OPID_CLIENT_SECRET: 
  SECRET_JITSI_KEY: 
  SECRET_KEY: eW91clNlY3JldEtleTIwMjA=
  TURN_STATIC_AUTH_SECRET: 
